
export PATH=${CMAKE_SOURCE_DIR}/bin:$PATH
export LD_LIBRARY_PATH=${CMAKE_SOURCE_DIR}/lib:$LD_LIBRARY_PATH
export PATH=${CMAKE_SOURCE_DIR}/include:$PATH
export CPATH=${CMAKE_SOURCE_DIR}/include:$CPATH
export ATP_PATH=${CMAKE_SOURCE_DIR}/bin/
export ATP_LIB=${CMAKE_SOURCE_DIR}/lib
